import java.lang.NumberFormatException

fun main() {

    /*

    Practice Activity 4
    Formulate program SalesDiscount for a particular sales range generated by sale.
    Follow the given discount range:

    Price range             Discount
    0 - 10,000              0%
    10,001 - 20,000         5%
    20,001 - 50,000         10%
    50,001 - 100,000        15%
    Greater than 100,000    20%

    Sample Input/Output:
    Enter product: modem router
    Enter price : 14500.50
    Price of modem router is 14,500.50
    Discount is 725.02
    Net Price is 13,775.48

     */

    // Declarations
    var product : String = ""
    var price : Double = 0.0
    var flag : Boolean = true

    //Enter Details
    var discount = ComputeDiscount()

    while (flag == true) {

        if(product == "") {
            print("Enter Product: ")
            product = readln()
        } else {
            println("Enter Product: $product")
        }

        if (product.checkIfString() == "true") {
            flag = false
            try {
                print("Enter Price: ")
                price = readln().toDouble()
                println(discount.getPrice(price))
            } catch (e: NumberFormatException) {
                flag = true
                println(e.message)
                println("Input amount only!")
            }

        } else {
            flag = true
            product = ""
            println("Invalid Product Name!")
        }

    }


}

class ComputeDiscount() {

    fun getPrice(price : Double) : String {

        var discount: Double = 0.0
        var net: Double = 0.0
        var discountPercentage : String = ""

        // Computation
        if ((price >= 0.00) && (price <= 10000.00)) {
            discount = price * 0.00
            net = price - discount
            discountPercentage = "0%"
        } else if ((price >= 10001.00) && (price <= 20000.00)) {
            discount = price * 0.05
            net = price - discount
            discountPercentage = "5%"
        } else if ((price >= 20001.00) && (price <= 50000.00)) {
            discount = price * 0.10
            net = price - discount
            discountPercentage = "10%"
        } else if ((price >= 50001.00) && (price <= 100000.00)) {
            discount = price * 0.15
            net = price - discount
            discountPercentage = "15%"
        } else if (price > 100000.00) {
            discount = price * 0.20
            net = price - discount
            discountPercentage = "20%"
        } else {
            net = 0.0
        }

        println("You have a $discountPercentage of ${String.format("%,.2f", discount)}, so your net pay is ${String.format("%,.2f", net)}")
        return discountPercentage

    }

}

fun String.checkIfString(): Any {
    var v = toIntOrNull()
    return when(v) {
        null -> "true"
        else -> "false"
    }
}