fun main() {

    /*

    Practice Activity 4
    Formulate program SalesDiscount for a particular sales range generated by sale.
    Follow the given discount range:


    Price range             Discount
    0 - 10,000              0%
    10,001 - 20,000         5%
    20,001 - 50,000         10%
    50,001 - 100,000        15%
    Greater than 100,000    20%

    Sample Input/Output:
    Enter product: modem router
    Enter price : 14500.50
    Price of modem router is 14,500.50
    Discount is 725.02
    Net Price is 13,775.48

     */

    // Declarations
    var discount : Double = 0.00
    var net : Double = 0.00

    // Enter Details
    print("Enter Product: ")
    var product : String = readln()
    print("Enter Price: ")
    var price : Double = readln().toDouble()

    // Computation
    if((price >= 0.00) && (price <= 10000.00)) {
        discount = price * 0.00
        net = price - discount
    } else if((price >= 10001.00) && (price <= 20000.00)) {
        discount = price * 0.05
        net = price - discount
    } else if((price >= 20000.00) && (price <= 50000.00)) {
        discount = price * 0.10
        net = price - discount
    } else if((price >= 50001.00) && (price <= 100000.00)) {
        discount = price * 0.15
        net = price - discount
    } else if(price > 100000.00) {
        discount = price * 0.20
        net = price - discount
    }else {
        println("Invalid Price")
    }

    println("Price of $product is " + String.format("%,.2f", price))
    println("Discount is " + String.format("%,.2f", discount))
    println("Net price is " + String.format("%,.2f", net))
}